/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlinx.datetime.Clock
import kotlinx.datetime.Instant

class LibraryApi {
    fun whatTimeIsIt(): Instant {
        return Clock.System.now()
    }
}
